/** Shared list for register + send-money phone inputs (searchable dial countries). */

export interface Country {
  code: string;
  name: string;
  dialCode: string;
  minDigits: number;
  maxDigits: number;
}

export const ALL_COUNTRIES: Country[] = [
  {
    code: "AF",
    name: "Afghanistan",
    dialCode: "93",
    minDigits: 9,
    maxDigits: 9,
  },
  { code: "AL", name: "Albania", dialCode: "355", minDigits: 9, maxDigits: 9 },
  { code: "DZ", name: "Algeria", dialCode: "213", minDigits: 9, maxDigits: 9 },
  {
    code: "AR",
    name: "Argentina",
    dialCode: "54",
    minDigits: 10,
    maxDigits: 10,
  },
  { code: "AU", name: "Australia", dialCode: "61", minDigits: 9, maxDigits: 9 },
  { code: "AT", name: "Austria", dialCode: "43", minDigits: 10, maxDigits: 13 },
  {
    code: "BD",
    name: "Bangladesh",
    dialCode: "880",
    minDigits: 10,
    maxDigits: 10,
  },
  { code: "BE", name: "Belgium", dialCode: "32", minDigits: 9, maxDigits: 9 },
  { code: "BR", name: "Brazil", dialCode: "55", minDigits: 10, maxDigits: 11 },
  { code: "CA", name: "Canada", dialCode: "1", minDigits: 10, maxDigits: 10 },
  { code: "CN", name: "China", dialCode: "86", minDigits: 11, maxDigits: 11 },
  {
    code: "CO",
    name: "Colombia",
    dialCode: "57",
    minDigits: 10,
    maxDigits: 10,
  },
  { code: "EG", name: "Egypt", dialCode: "20", minDigits: 10, maxDigits: 10 },
  { code: "FR", name: "France", dialCode: "33", minDigits: 9, maxDigits: 9 },
  { code: "DE", name: "Germany", dialCode: "49", minDigits: 10, maxDigits: 11 },
  { code: "GH", name: "Ghana", dialCode: "233", minDigits: 9, maxDigits: 9 },
  { code: "GR", name: "Greece", dialCode: "30", minDigits: 10, maxDigits: 10 },
  {
    code: "HK",
    name: "Hong Kong",
    dialCode: "852",
    minDigits: 8,
    maxDigits: 8,
  },
  { code: "IN", name: "India", dialCode: "91", minDigits: 10, maxDigits: 10 },
  {
    code: "ID",
    name: "Indonesia",
    dialCode: "62",
    minDigits: 5,
    maxDigits: 12,
  },
  { code: "IE", name: "Ireland", dialCode: "353", minDigits: 9, maxDigits: 9 },
  { code: "IT", name: "Italy", dialCode: "39", minDigits: 9, maxDigits: 10 },
  { code: "JP", name: "Japan", dialCode: "81", minDigits: 10, maxDigits: 10 },
  { code: "KE", name: "Kenya", dialCode: "254", minDigits: 9, maxDigits: 9 },
  {
    code: "SS",
    name: "South Sudan",
    dialCode: "211",
    minDigits: 9,
    maxDigits: 9,
  },
  { code: "KW", name: "Kuwait", dialCode: "965", minDigits: 8, maxDigits: 8 },
  { code: "LB", name: "Lebanon", dialCode: "961", minDigits: 7, maxDigits: 8 },
  { code: "LY", name: "Libya", dialCode: "218", minDigits: 9, maxDigits: 9 },
  { code: "MY", name: "Malaysia", dialCode: "60", minDigits: 9, maxDigits: 10 },
  { code: "MX", name: "Mexico", dialCode: "52", minDigits: 10, maxDigits: 10 },
  { code: "MA", name: "Morocco", dialCode: "212", minDigits: 9, maxDigits: 9 },
  {
    code: "NL",
    name: "Netherlands",
    dialCode: "31",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "NZ",
    name: "New Zealand",
    dialCode: "64",
    minDigits: 8,
    maxDigits: 10,
  },
  {
    code: "NG",
    name: "Nigeria",
    dialCode: "234",
    minDigits: 10,
    maxDigits: 10,
  },
  { code: "NO", name: "Norway", dialCode: "47", minDigits: 8, maxDigits: 8 },
  {
    code: "PK",
    name: "Pakistan",
    dialCode: "92",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "PH",
    name: "Philippines",
    dialCode: "63",
    minDigits: 10,
    maxDigits: 10,
  },
  { code: "PL", name: "Poland", dialCode: "48", minDigits: 9, maxDigits: 9 },
  { code: "PT", name: "Portugal", dialCode: "351", minDigits: 9, maxDigits: 9 },
  { code: "QA", name: "Qatar", dialCode: "974", minDigits: 8, maxDigits: 8 },
  { code: "RO", name: "Romania", dialCode: "40", minDigits: 10, maxDigits: 10 },
  { code: "RU", name: "Russia", dialCode: "7", minDigits: 10, maxDigits: 10 },
  {
    code: "SA",
    name: "Saudi Arabia",
    dialCode: "966",
    minDigits: 9,
    maxDigits: 9,
  },
  { code: "SG", name: "Singapore", dialCode: "65", minDigits: 8, maxDigits: 8 },
  {
    code: "ZA",
    name: "South Africa",
    dialCode: "27",
    minDigits: 9,
    maxDigits: 9,
  },
  {
    code: "KR",
    name: "South Korea",
    dialCode: "82",
    minDigits: 9,
    maxDigits: 10,
  },
  { code: "ES", name: "Spain", dialCode: "34", minDigits: 9, maxDigits: 9 },
  { code: "LK", name: "Sri Lanka", dialCode: "94", minDigits: 9, maxDigits: 9 },
  { code: "SE", name: "Sweden", dialCode: "46", minDigits: 9, maxDigits: 9 },
  {
    code: "CH",
    name: "Switzerland",
    dialCode: "41",
    minDigits: 9,
    maxDigits: 9,
  },
  { code: "TW", name: "Taiwan", dialCode: "886", minDigits: 9, maxDigits: 9 },
  { code: "TZ", name: "Tanzania", dialCode: "255", minDigits: 9, maxDigits: 9 },
  { code: "TH", name: "Thailand", dialCode: "66", minDigits: 9, maxDigits: 9 },
  { code: "TR", name: "Turkey", dialCode: "90", minDigits: 10, maxDigits: 10 },
  {
    code: "AE",
    name: "United Arab Emirates",
    dialCode: "971",
    minDigits: 9,
    maxDigits: 9,
  },
  { code: "UG", name: "Uganda", dialCode: "256", minDigits: 9, maxDigits: 9 },
  {
    code: "GB",
    name: "United Kingdom",
    dialCode: "44",
    minDigits: 10,
    maxDigits: 10,
  },
  {
    code: "US",
    name: "United States",
    dialCode: "1",
    minDigits: 10,
    maxDigits: 10,
  },
  { code: "VN", name: "Vietnam", dialCode: "84", minDigits: 9, maxDigits: 10 },
  { code: "ZW", name: "Zimbabwe", dialCode: "263", minDigits: 9, maxDigits: 9 },
];
